# Generated by Django 4.1.4 on 2022-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_note_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
